# Generated by Django 5.2.3 on 2025-07-01 16:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la communauté', max_length=100)),
                ('description', models.TextField(help_text='Description de la communauté')),
                ('zone_geo', models.CharField(help_text='Zone géographique concernée', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False, help_text='Indique si la communauté est privée')),
                ('theme', models.CharField(help_text='Thème de la communauté', max_length=50)),
                ('admin', models.ForeignKey(help_text='Administrateur de la communauté', on_delete=django.db.models.deletion.CASCADE, related_name='admin_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'communauté',
                'verbose_name_plural': 'communautés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_depart', models.DateTimeField(help_text='Date et heure de départ')),
                ('temps_arrive', models.DateTimeField(help_text="Date et heure d'arrivée estimée")),
                ('origine', models.CharField(help_text='Lieu de départ', max_length=100)),
                ('destination', models.CharField(help_text="Lieu d'arrivée", max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix du trajet par passager', max_digits=6)),
                ('places_dispo', models.PositiveIntegerField(help_text='Nombre de places disponibles')),
                ('statut', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='SCHEDULED', help_text='État actuel du trajet', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communaute', models.ForeignKey(blank=True, help_text='Communauté liée au trajet (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.community')),
                ('conducteur', models.ForeignKey(help_text='Conducteur proposant le trajet', on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(help_text='Véhicule utilisé pour le trajet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='user_management.vehicule')),
            ],
            options={
                'verbose_name': 'trajet',
                'verbose_name_plural': 'trajets',
                'ordering': ['-temps_depart'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_reserv', models.PositiveIntegerField(default=1, help_text='Nombre de places réservées')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé')], default='PENDING', help_text='État de la réservation', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(help_text='Passager effectuant la réservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(help_text='Trajet réservé', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.trip')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('idRate', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(help_text='Note de 1 à 5 étoiles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaires', models.TextField(blank=True, help_text='Commentaire optionnel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_user', models.ForeignKey(help_text='Utilisateur qui reçoit la note', on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='Utilisateur qui donne la note', on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(help_text="Trajet concerné par l'évaluation", on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.trip')),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
                'db_table': 'rating',
                'indexes': [models.Index(fields=['rated_user', 'score'], name='rating_rated_u_ef8d01_idx'), models.Index(fields=['trip'], name='rating_trip_id_909eab_idx')],
                'unique_together': {('reviewer', 'rated_user', 'trip')},
            },
        ),
    ]
