# Generated by Django 5.2.3 on 2025-07-02 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='admin',
            field=models.ForeignKey(help_text='Administrateur de la communauté', on_delete=django.db.models.deletion.CASCADE, related_name='admin_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_user',
            field=models.ForeignKey(help_text='Utilisateur qui reçoit la note', on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='reviewer',
            field=models.ForeignKey(help_text='Utilisateur qui donne la note', on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='passenger',
            field=models.ForeignKey(help_text='Passager effectuant la réservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='communaute',
            field=models.ForeignKey(blank=True, help_text='Communauté liée au trajet (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.community'),
        ),
        migrations.AddField(
            model_name='trip',
            name='conducteur',
            field=models.ForeignKey(help_text='Conducteur proposant le trajet', on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicule',
            field=models.ForeignKey(help_text='Véhicule utilisé pour le trajet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='user_management.vehicule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trip',
            field=models.ForeignKey(help_text='Trajet réservé', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.trip'),
        ),
        migrations.AddField(
            model_name='rating',
            name='trip',
            field=models.ForeignKey(help_text="Trajet concerné par l'évaluation", on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.trip'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user', 'score'], name='rating_rated_u_ef8d01_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['trip'], name='rating_trip_id_909eab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('reviewer', 'rated_user', 'trip')},
        ),
    ]
